// This file is auto-generated by @hey-api/openapi-ts

export const $ArtistInfoInLecture = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        nickname: {
            type: 'string',
            title: 'Nickname'
        },
        is_artist: {
            type: 'boolean',
            title: 'Is Artist'
        }
    },
    type: 'object',
    required: ['id', 'nickname', 'is_artist'],
    title: 'ArtistInfoInLecture'
} as const;

export const $Body_auth_redis_login_user_auth_login_post = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_auth_redis_login_user_auth_login_post'
} as const;

export const $Body_reset_forgot_password_user_auth_forgot_password_post = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'Body_reset_forgot_password_user_auth_forgot_password_post'
} as const;

export const $Body_reset_reset_password_user_auth_reset_password_post = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['token', 'password'],
    title: 'Body_reset_reset_password_user_auth_reset_password_post'
} as const;

export const $CreateLectureBody = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            type: 'string',
            title: 'Description',
            default: '새로운 강의'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'CreateLectureBody'
} as const;

export const $CreateLectureResponseSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/LectureDetail'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'CreateLectureResponseSchema'
} as const;

export const $ErrorModel = {
    properties: {
        detail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                }
            ],
            title: 'Detail'
        }
    },
    type: 'object',
    required: ['detail'],
    title: 'ErrorModel'
} as const;

export const $FetchRecommendedLecuturesSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/LectureInList'
            },
            type: 'array',
            title: 'Data'
        },
        meta: {
            '$ref': '#/components/schemas/PaginationMeta'
        }
    },
    type: 'object',
    required: ['data', 'meta'],
    title: 'FetchRecommendedLecuturesSchema'
} as const;

export const $GetArtistsResponse = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserArtistInfo'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'GetArtistsResponse'
} as const;

export const $GetLectureSchema = {
    properties: {
        data: {
            '$ref': '#/components/schemas/LectureDetail'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'GetLectureSchema'
} as const;

export const $HTTPValidationError = {
    properties: {
        errors: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Errors'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $LectureAccessStatus = {
    properties: {
        accessible: {
            type: 'boolean',
            title: 'Accessible'
        },
        reason: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['unlimited', 'ticket_used', 'no_ticket', 'ticket_expired']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        },
        ticket_count: {
            type: 'integer',
            title: 'Ticket Count'
        }
    },
    type: 'object',
    required: ['accessible', 'ticket_count'],
    title: 'LectureAccessStatus'
} as const;

export const $LectureDetail = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        artist: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ArtistInfoInLecture'
                },
                {
                    type: 'null'
                }
            ]
        },
        lessons: {
            items: {
                '$ref': '#/components/schemas/LessonInLecture'
            },
            type: 'array',
            title: 'Lessons'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        thumbnail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thumbnail'
        },
        tags: {
            anyOf: [
                {
                    prefixItems: [
                        {
                            type: 'string',
                            enum: ['원곡카피', '해석버전', '기본기']
                        },
                        {
                            type: 'string',
                            enum: ['Easy', 'Intermediate', 'Advanced']
                        }
                    ],
                    type: 'array',
                    maxItems: 2,
                    minItems: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        length_sec: {
            type: 'integer',
            title: 'Length Sec'
        },
        lecture_count: {
            type: 'integer',
            title: 'Lecture Count'
        },
        time_created: {
            type: 'string',
            format: 'date-time',
            title: 'Time Created'
        },
        time_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Time Updated'
        }
    },
    type: 'object',
    required: ['id', 'title', 'artist', 'lessons', 'description', 'thumbnail', 'tags', 'length_sec', 'lecture_count', 'time_created', 'time_updated'],
    title: 'LectureDetail'
} as const;

export const $LectureInList = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        thumbnail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thumbnail'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        artist: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ArtistInfoInLecture'
                },
                {
                    type: 'null'
                }
            ]
        },
        lessons: {
            items: {
                '$ref': '#/components/schemas/LessonInLecture'
            },
            type: 'array',
            title: 'Lessons'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        tags: {
            anyOf: [
                {
                    prefixItems: [
                        {
                            type: 'string',
                            enum: ['원곡카피', '해석버전', '기본기']
                        },
                        {
                            type: 'string',
                            enum: ['Easy', 'Intermediate', 'Advanced']
                        }
                    ],
                    type: 'array',
                    maxItems: 2,
                    minItems: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        length_sec: {
            type: 'integer',
            title: 'Length Sec'
        },
        lecture_count: {
            type: 'integer',
            title: 'Lecture Count'
        },
        time_created: {
            type: 'string',
            format: 'date-time',
            title: 'Time Created'
        },
        time_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Time Updated'
        }
    },
    type: 'object',
    required: ['id', 'thumbnail', 'title', 'artist', 'lessons', 'description', 'tags', 'length_sec', 'lecture_count', 'time_created', 'time_updated'],
    title: 'LectureInList'
} as const;

export const $LectureInfo = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        total_sessions: {
            type: 'integer',
            title: 'Total Sessions'
        }
    },
    type: 'object',
    required: ['id', 'title', 'total_sessions'],
    title: 'LectureInfo'
} as const;

export const $LessonInLecture = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        length_sec: {
            type: 'integer',
            title: 'Length Sec'
        },
        lecture_ordering: {
            type: 'integer',
            title: 'Lecture Ordering'
        },
        time_created: {
            type: 'string',
            format: 'date-time',
            title: 'Time Created'
        },
        time_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Time Updated'
        }
    },
    type: 'object',
    required: ['id', 'title', 'length_sec', 'lecture_ordering', 'time_created', 'time_updated'],
    title: 'LessonInLecture'
} as const;

export const $OAuth2AuthorizeResponse = {
    properties: {
        authorization_url: {
            type: 'string',
            title: 'Authorization Url'
        }
    },
    type: 'object',
    required: ['authorization_url'],
    title: 'OAuth2AuthorizeResponse'
} as const;

export const $PaginationMeta = {
    properties: {
        total_items: {
            type: 'integer',
            title: 'Total Items'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        curr_page: {
            type: 'integer',
            title: 'Curr Page'
        },
        per_page: {
            type: 'integer',
            title: 'Per Page'
        }
    },
    type: 'object',
    required: ['total_items', 'total_pages', 'curr_page', 'per_page'],
    title: 'PaginationMeta'
} as const;

export const $PlayingGuideStep = {
    properties: {
        step: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Step'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        start_time: {
            type: 'string',
            title: 'Start Time'
        },
        end_time: {
            type: 'string',
            title: 'End Time'
        },
        tip: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tip'
        }
    },
    type: 'object',
    required: ['step', 'title', 'description', 'start_time', 'end_time'],
    title: 'PlayingGuideStep'
} as const;

export const $SessionDetailResponse = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        session_type: {
            '$ref': '#/components/schemas/SessionType'
        },
        session_type_label: {
            type: 'string',
            title: 'Session Type Label'
        },
        lecture_ordering: {
            type: 'integer',
            title: 'Lecture Ordering'
        },
        length_sec: {
            type: 'integer',
            title: 'Length Sec'
        },
        lecture: {
            '$ref': '#/components/schemas/LectureInfo'
        },
        video: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/VideoInfo'
                },
                {
                    type: 'null'
                }
            ]
        },
        sheetmusic_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sheetmusic Url'
        },
        sync_offset: {
            type: 'integer',
            title: 'Sync Offset'
        },
        subtitles: {
            items: {
                '$ref': '#/components/schemas/Subtitle'
            },
            type: 'array',
            title: 'Subtitles'
        },
        playing_guide: {
            items: {
                '$ref': '#/components/schemas/PlayingGuideStep'
            },
            type: 'array',
            title: 'Playing Guide'
        },
        navigation: {
            '$ref': '#/components/schemas/SessionNavigation'
        }
    },
    type: 'object',
    required: ['id', 'title', 'session_type', 'session_type_label', 'lecture_ordering', 'length_sec', 'lecture', 'video', 'sheetmusic_url', 'sync_offset', 'subtitles', 'playing_guide', 'navigation'],
    title: 'SessionDetailResponse'
} as const;

export const $SessionNavigation = {
    properties: {
        prev_session_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prev Session Id'
        },
        next_session_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Session Id'
        }
    },
    type: 'object',
    required: ['prev_session_id', 'next_session_id'],
    title: 'SessionNavigation'
} as const;

export const $SessionType = {
    type: 'string',
    enum: ['PLAY', 'TALK', 'JAM', 'BASIC', 'SHEET'],
    title: 'SessionType'
} as const;

export const $Subtitle = {
    properties: {
        timestamp_ms: {
            type: 'integer',
            minimum: 0,
            title: 'Timestamp Ms'
        },
        text: {
            type: 'string',
            title: 'Text'
        }
    },
    type: 'object',
    required: ['timestamp_ms', 'text'],
    title: 'Subtitle'
} as const;

export const $UserArtistInfo = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        nickname: {
            type: 'string',
            title: 'Nickname'
        },
        time_created: {
            type: 'string',
            format: 'date-time',
            title: 'Time Created'
        },
        lectures: {
            items: {
                '$ref': '#/components/schemas/LectureInList'
            },
            type: 'array',
            title: 'Lectures'
        }
    },
    type: 'object',
    required: ['id', 'nickname', 'time_created', 'lectures'],
    title: 'UserArtistInfo'
} as const;

export const $UserRead = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        },
        nickname: {
            type: 'string',
            title: 'Nickname'
        },
        is_artist: {
            type: 'boolean',
            title: 'Is Artist'
        }
    },
    type: 'object',
    required: ['id', 'email', 'is_superuser', 'nickname', 'is_artist'],
    title: 'UserRead'
} as const;

export const $UserUpdate = {
    properties: {
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        is_verified: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Verified'
        },
        nickname: {
            type: 'string',
            title: 'Nickname'
        }
    },
    type: 'object',
    required: ['nickname'],
    title: 'UserUpdate'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const $VideoInfo = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: ['url', 'type', 'expires_at'],
    title: 'VideoInfo'
} as const;

export const $VideoURLResponse = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        type: {
            type: 'string',
            enum: ['hls', 'direct'],
            title: 'Type'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: ['url', 'type', 'expires_at'],
    title: 'VideoURLResponse'
} as const;