// This file is auto-generated by @hey-api/openapi-ts

export type ArtistInfoInLecture = {
    id: string;
    nickname: string;
    is_artist: boolean;
};

export type Body_auth_redis_login_user_auth_login_post = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type Body_reset_forgot_password_user_auth_forgot_password_post = {
    email: string;
};

export type Body_reset_reset_password_user_auth_reset_password_post = {
    token: string;
    password: string;
};

export type Body_upload_lesson_sheetmusic_lesson__lesson_id__sheetmusic_post = {
    file: (Blob | File);
};

export type Body_upload_lesson_video_lesson__lesson_id__video_post = {
    file: (Blob | File);
};

export type CreateLectureBody = {
    title: string;
    description?: string;
};

export type CreateLectureResponseSchema = {
    data: LectureDetail;
};

export type CreateLessonBody = {
    lecture_id: number;
    title: string;
    length_sec?: number;
    text?: string;
    lecture_ordering?: number;
    session_type?: SessionType | null;
    sync_offset?: number;
    subtitles?: Array<Subtitle>;
    playing_guide?: Array<PlayingGuideStep>;
};

export type CurationData = {
    TRENDING: Array<LectureInList>;
    NEW: Array<LectureInList>;
};

export type CurationSection = 'TRENDING' | 'NEW';

export type ErrorModel = {
    detail: string | {
    [key: string]: (string);
};
};

export type FetchRecommendedLecuturesSchema = {
    data: Array<LectureInList>;
    meta: PaginationMeta;
};

export type GetArtistsResponse = {
    data: Array<UserArtistInfo>;
};

export type GetCurationSchema = {
    data: CurationData;
};

export type GetLectureSchema = {
    data: LectureDetail;
};

export type HTTPValidationError = {
    errors?: Array<ValidationError>;
};

export type LectureAccessStatus = {
    accessible: boolean;
    reason?: 'unlimited' | 'ticket_used' | 'no_ticket' | 'ticket_expired' | null;
    expires_at?: string | null;
    ticket_count: number;
};

export type LectureDetail = {
    id: number;
    title: string;
    artist: ArtistInfoInLecture | null;
    lessons: Array<LessonInLecture>;
    description: string;
    thumbnail: string | null;
    tags: unknown[] | null;
    length_sec: number;
    lecture_count: number;
    time_created: string;
    time_updated: string;
    progress?: LectureProgressData | null;
};

export type LectureInList = {
    id: number;
    thumbnail: string | null;
    title: string;
    artist: ArtistInfoInLecture | null;
    lessons: Array<LessonInLecture>;
    description: string;
    tags: unknown[] | null;
    length_sec: number;
    lecture_count: number;
    time_created: string;
    time_updated: string;
};

export type LectureInfo = {
    id: number;
    title: string;
    total_sessions: number;
};

export type LectureProgressData = {
    completed_count: number;
    total_count: number;
    percent: number;
    next_lesson_id: number | null;
    completed_lesson_ids: Array<(number)>;
    lessons: Array<LessonProgressItem>;
    resume_lesson_id: number | null;
    resume_position_sec: number;
};

export type LessonAdminDetail = {
    id: number;
    lecture_id: number;
    title: string;
    length_sec: number;
    text: string | null;
    lecture_ordering: number;
    session_type: SessionType | null;
    sheetmusic_url: string | null;
    video_url: string | null;
    sync_offset: number;
    subtitles: Array<Subtitle>;
    playing_guide: Array<PlayingGuideStep>;
};

export type LessonAdminSchema = {
    data: LessonAdminDetail;
};

export type LessonInLecture = {
    id: number;
    title: string;
    length_sec: number;
    lecture_ordering: number;
    time_created: string;
    time_updated: string;
};

export type LessonProgressItem = {
    lesson_id: number;
    percent: number;
    completed: boolean;
    last_position_sec: number;
};

export type OAuth2AuthorizeResponse = {
    authorization_url: string;
};

export type PaginationMeta = {
    total_items: number;
    total_pages: number;
    curr_page: number;
    per_page: number;
};

export type PlayingGuideStep = {
    step: number;
    title: string;
    description: string;
    start_time: string;
    end_time: string;
    tip?: string | null;
};

export type PositionReport = {
    position_sec: number;
    duration_sec: number;
};

export type SessionDetailResponse = {
    id: number;
    title: string;
    session_type: SessionType;
    session_type_label: string;
    lecture_ordering: number;
    length_sec: number;
    lecture: LectureInfo;
    video: VideoInfo | null;
    sheetmusic_url: string | null;
    sync_offset: number;
    subtitles: Array<Subtitle>;
    playing_guide: Array<PlayingGuideStep>;
    navigation: SessionNavigation;
};

export type SessionNavigation = {
    prev_session_id: number | null;
    next_session_id: number | null;
    next_session_title?: string | null;
};

export type SessionType = 'PLAY' | 'TALK' | 'JAM' | 'BASIC' | 'SHEET';

export type SetCurationBody = {
    lecture_ids: Array<(number)>;
};

export type Subtitle = {
    timestamp_ms: number;
    text: string;
};

export type UpdateLectureBody = {
    title?: string | null;
    description?: string | null;
    tags?: unknown[] | null;
    thumbnail?: string | null;
};

export type UpdateLessonBody = {
    title?: string | null;
    length_sec?: number | null;
    text?: string | null;
    lecture_ordering?: number | null;
    session_type?: SessionType | null;
    sync_offset?: number | null;
    subtitles?: Array<Subtitle> | null;
    playing_guide?: Array<PlayingGuideStep> | null;
};

export type UserArtistInfo = {
    id: string;
    nickname: string;
    time_created: string;
    lectures: Array<LectureInList>;
};

export type UserRead = {
    id: string;
    email: string;
    is_active?: boolean;
    is_superuser: boolean;
    is_verified?: boolean;
    nickname: string;
    is_artist: boolean;
};

export type UserUpdate = {
    password?: string | null;
    email?: string | null;
    is_active?: boolean | null;
    is_superuser?: boolean | null;
    is_verified?: boolean | null;
    nickname: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type VideoInfo = {
    url: string;
    type: string;
    expires_at: string;
};

export type VideoURLResponse = {
    url: string;
    type: 'hls' | 'direct';
    expires_at: string;
};

export type type = 'hls' | 'direct';

export type GetArtistsUserArtistsGetResponse = GetArtistsResponse;

export type AuthRedisLoginUserAuthLoginPostData = {
    formData: Body_auth_redis_login_user_auth_login_post;
};

export type AuthRedisLoginUserAuthLoginPostResponse = unknown | void;

export type AuthRedisLogoutUserAuthLogoutPostResponse = unknown | void;

export type ResetForgotPasswordUserAuthForgotPasswordPostData = {
    requestBody: Body_reset_forgot_password_user_auth_forgot_password_post;
};

export type ResetForgotPasswordUserAuthForgotPasswordPostResponse = unknown;

export type ResetResetPasswordUserAuthResetPasswordPostData = {
    requestBody: Body_reset_reset_password_user_auth_reset_password_post;
};

export type ResetResetPasswordUserAuthResetPasswordPostResponse = unknown;

export type OauthGoogleRedisAuthorizeUserOauthGoogleAuthorizeGetData = {
    scopes?: Array<(string)>;
};

export type OauthGoogleRedisAuthorizeUserOauthGoogleAuthorizeGetResponse = OAuth2AuthorizeResponse;

export type OauthGoogleRedisCallbackUserOauthGoogleCallbackGetData = {
    code?: string | null;
    codeVerifier?: string | null;
    error?: string | null;
    state?: string | null;
};

export type OauthGoogleRedisCallbackUserOauthGoogleCallbackGetResponse = unknown;

export type UsersCurrentUserUserMeGetResponse = UserRead;

export type UsersPatchCurrentUserUserMePatchData = {
    requestBody: UserUpdate;
};

export type UsersPatchCurrentUserUserMePatchResponse = UserRead;

export type UsersUserUserIdGetData = {
    id: string;
};

export type UsersUserUserIdGetResponse = UserRead;

export type UsersPatchUserUserIdPatchData = {
    id: string;
    requestBody: UserUpdate;
};

export type UsersPatchUserUserIdPatchResponse = UserRead;

export type UsersDeleteUserUserIdDeleteData = {
    id: string;
};

export type UsersDeleteUserUserIdDeleteResponse = void;

export type GetLecturesLectureGetData = {
    page?: number;
    perPage?: number;
};

export type GetLecturesLectureGetResponse = FetchRecommendedLecuturesSchema;

export type CreateLectureLecturePostData = {
    requestBody: CreateLectureBody;
};

export type CreateLectureLecturePostResponse = CreateLectureResponseSchema;

export type GetLectureLectureLectureIdGetData = {
    lectureId: number;
};

export type GetLectureLectureLectureIdGetResponse = GetLectureSchema;

export type UpdateLectureLectureLectureIdPatchData = {
    lectureId: number;
    requestBody: UpdateLectureBody;
};

export type UpdateLectureLectureLectureIdPatchResponse = GetLectureSchema;

export type GetLessonVideoLessonLessonIdVideoGetData = {
    lessonId: number;
};

export type GetLessonVideoLessonLessonIdVideoGetResponse = VideoURLResponse;

export type UploadLessonVideoLessonLessonIdVideoPostData = {
    formData: Body_upload_lesson_video_lesson__lesson_id__video_post;
    lessonId: number;
};

export type UploadLessonVideoLessonLessonIdVideoPostResponse = LessonAdminSchema;

export type CreateLessonLessonPostData = {
    requestBody: CreateLessonBody;
};

export type CreateLessonLessonPostResponse = LessonAdminSchema;

export type UpdateLessonLessonLessonIdPatchData = {
    lessonId: number;
    requestBody: UpdateLessonBody;
};

export type UpdateLessonLessonLessonIdPatchResponse = LessonAdminSchema;

export type UploadLessonSheetmusicLessonLessonIdSheetmusicPostData = {
    formData: Body_upload_lesson_sheetmusic_lesson__lesson_id__sheetmusic_post;
    lessonId: number;
};

export type UploadLessonSheetmusicLessonLessonIdSheetmusicPostResponse = LessonAdminSchema;

export type GetSessionDetailSessionSessionIdGetData = {
    sessionId: number;
};

export type GetSessionDetailSessionSessionIdGetResponse = SessionDetailResponse;

export type GetLectureAccessStatusTicketLectureLectureIdGetData = {
    lectureId: number;
};

export type GetLectureAccessStatusTicketLectureLectureIdGetResponse = LectureAccessStatus;

export type UseTicketTicketLectureLectureIdPostData = {
    lectureId: number;
};

export type UseTicketTicketLectureLectureIdPostResponse = LectureAccessStatus;

export type GetCurationCurationGetResponse = GetCurationSchema;

export type SetCurationCurationSectionPutData = {
    requestBody: SetCurationBody;
    section: CurationSection;
};

export type SetCurationCurationSectionPutResponse = unknown;

export type MarkLessonCompleteProgressLessonLessonIdPostData = {
    lessonId: number;
};

export type MarkLessonCompleteProgressLessonLessonIdPostResponse = LectureProgressData;

export type ReportLessonPositionProgressLessonLessonIdPositionPutData = {
    lessonId: number;
    requestBody: PositionReport;
};

export type ReportLessonPositionProgressLessonLessonIdPositionPutResponse = LectureProgressData;

export type PongPingGetResponse = unknown;

export type AuthPongPingAuthGetResponse = unknown;

export type $OpenApiTs = {
    '/user/artists': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: GetArtistsResponse;
            };
        };
    };
    '/user/auth/login': {
        post: {
            req: AuthRedisLoginUserAuthLoginPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * No Content
                 */
                204: void;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/user/auth/logout': {
        post: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * No Content
                 */
                204: void;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
            };
        };
    };
    '/user/auth/forgot-password': {
        post: {
            req: ResetForgotPasswordUserAuthForgotPasswordPostData;
            res: {
                /**
                 * Successful Response
                 */
                202: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/user/auth/reset-password': {
        post: {
            req: ResetResetPasswordUserAuthResetPasswordPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/user/oauth/google/authorize': {
        get: {
            req: OauthGoogleRedisAuthorizeUserOauthGoogleAuthorizeGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: OAuth2AuthorizeResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/user/oauth/google/callback': {
        get: {
            req: OauthGoogleRedisCallbackUserOauthGoogleCallbackGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/user/me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: UserRead;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
            };
        };
        patch: {
            req: UsersPatchCurrentUserUserMePatchData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserRead;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/user/{id}': {
        get: {
            req: UsersUserUserIdGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserRead;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
                /**
                 * Not a superuser.
                 */
                403: unknown;
                /**
                 * The user does not exist.
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: UsersPatchUserUserIdPatchData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserRead;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
                /**
                 * Not a superuser.
                 */
                403: unknown;
                /**
                 * The user does not exist.
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: UsersDeleteUserUserIdDeleteData;
            res: {
                /**
                 * Successful Response
                 */
                204: void;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
                /**
                 * Not a superuser.
                 */
                403: unknown;
                /**
                 * The user does not exist.
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/lecture': {
        get: {
            req: GetLecturesLectureGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: FetchRecommendedLecuturesSchema;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: CreateLectureLecturePostData;
            res: {
                /**
                 * Successful Response
                 */
                201: CreateLectureResponseSchema;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/lecture/{lecture_id}': {
        get: {
            req: GetLectureLectureLectureIdGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: GetLectureSchema;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: UpdateLectureLectureLectureIdPatchData;
            res: {
                /**
                 * Successful Response
                 */
                200: GetLectureSchema;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/lesson/{lesson_id}/video': {
        get: {
            req: GetLessonVideoLessonLessonIdVideoGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: VideoURLResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: UploadLessonVideoLessonLessonIdVideoPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: LessonAdminSchema;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/lesson': {
        post: {
            req: CreateLessonLessonPostData;
            res: {
                /**
                 * Successful Response
                 */
                201: LessonAdminSchema;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/lesson/{lesson_id}': {
        patch: {
            req: UpdateLessonLessonLessonIdPatchData;
            res: {
                /**
                 * Successful Response
                 */
                200: LessonAdminSchema;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/lesson/{lesson_id}/sheetmusic': {
        post: {
            req: UploadLessonSheetmusicLessonLessonIdSheetmusicPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: LessonAdminSchema;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/session/{session_id}': {
        get: {
            req: GetSessionDetailSessionSessionIdGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: SessionDetailResponse;
                /**
                 * Unauthorized
                 */
                401: unknown;
                /**
                 * Access denied
                 */
                403: unknown;
                /**
                 * Session not found
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/ticket/lecture/{lecture_id}': {
        get: {
            req: GetLectureAccessStatusTicketLectureLectureIdGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: LectureAccessStatus;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: UseTicketTicketLectureLectureIdPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: LectureAccessStatus;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/curation': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: GetCurationSchema;
            };
        };
    };
    '/curation/{section}': {
        put: {
            req: SetCurationCurationSectionPutData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/progress/lesson/{lesson_id}': {
        post: {
            req: MarkLessonCompleteProgressLessonLessonIdPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: LectureProgressData;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/progress/lesson/{lesson_id}/position': {
        put: {
            req: ReportLessonPositionProgressLessonLessonIdPositionPutData;
            res: {
                /**
                 * Successful Response
                 */
                200: LectureProgressData;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/ping': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/ping/auth': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
};