"""add relation tables

Revision ID: 957380a511ce
Revises: 03c3c986d062
Create Date: 2023-08-30 21:37:46.601679

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "957380a511ce"
down_revision = "03c3c986d062"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artist_x_lecture",
        sa.Column("artist_id", sa.UUID(), nullable=False),
        sa.Column("lecture_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lecture_id"],
            ["lecture.id"],
        ),
        sa.PrimaryKeyConstraint("artist_id", "lecture_id"),
    )
    op.drop_column("lecture", "artists")
    op.drop_column("user", "is_admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "lecture",
        sa.Column("artists", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_table("artist_x_lecture")
    # ### end Alembic commands ###
