"""drop access token table

Revision ID: 4ac0b0ed1beb
Revises: 957380a511ce
Create Date: 2023-11-03 18:01:19.049445

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4ac0b0ed1beb"
down_revision = "957380a511ce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_accesstoken_created_at", table_name="accesstoken")
    op.drop_table("accesstoken")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accesstoken",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("token", sa.VARCHAR(length=43), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="accesstoken_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token", name="accesstoken_pkey"),
    )
    op.create_index(
        "ix_accesstoken_created_at", "accesstoken", ["created_at"], unique=False
    )
    # ### end Alembic commands ###
