"""add timestamp

Revision ID: e390744887bf
Revises: 5c0ebdbbbf37
Create Date: 2023-07-30 22:01:34.306373

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e390744887bf"
down_revision = "5c0ebdbbbf37"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oauth_account", sa.Column("time_created", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "oauth_account", sa.Column("time_updated", sa.DateTime(), nullable=True)
    )
    op.add_column("user", sa.Column("time_created", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("time_updated", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "time_updated")
    op.drop_column("user", "time_created")
    op.drop_column("oauth_account", "time_updated")
    op.drop_column("oauth_account", "time_created")
    # ### end Alembic commands ###
