"""drop lecture_lesson_association

Revision ID: 3cf5570a9c36
Revises: 7e09fb186a47
Create Date: 2024-05-24 20:07:39.535873

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3cf5570a9c36"
down_revision = "7e09fb186a47"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("artist_x_lecture")
    op.drop_table("lecture_x_lesson")
    op.add_column("lecture", sa.Column("artist_id", sa.UUID(), nullable=True))
    op.create_foreign_key("lecture_user_fkey", "lecture", "user", ["artist_id"], ["id"])
    op.add_column("lesson", sa.Column("lecture_id", sa.Integer(), nullable=False))
    op.add_column("lesson", sa.Column("length_sec", sa.Integer(), nullable=False))
    op.add_column("lesson", sa.Column("lecture_ordering", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "lesson_lecture_fkey", "lesson", "lecture", ["lecture_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("lesson_lecture_fkey", "lesson", type_="foreignkey")
    op.drop_column("lesson", "lecture_ordering")
    op.drop_column("lesson", "length_sec")
    op.drop_column("lesson", "lecture_id")
    op.drop_constraint("lecture_user_fkey", "lecture", type_="foreignkey")
    op.drop_column("lecture", "artist_id")
    op.create_table(
        "lecture_x_lesson",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("lecture_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("lesson_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["lecture_id"], ["lecture.id"], name="lecture_x_lesson_lecture_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"], ["lesson.id"], name="lecture_x_lesson_lesson_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="lecture_x_lesson_pkey"),
    )
    op.create_table(
        "artist_x_lecture",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("artist_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("lecture_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"], ["user.id"], name="artist_x_lecture_artist_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["lecture_id"], ["lecture.id"], name="artist_x_lecture_lecture_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="artist_x_lecture_pkey"),
    )
    # ### end Alembic commands ###
