"""fix_lecture_lesson_relation

Revision ID: c5c94fba417a
Revises: 7e09fb186a47
Create Date: 2024-05-17 21:50:59.893016

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c5c94fba417a"
down_revision = "7e09fb186a47"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lecture_x_lesson",
        sa.Column("ordering", sa.Integer(), nullable=False, default=0),
    )
    op.add_column("lesson", sa.Column("lecture_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "lesson", "lecture", ["lecture_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "lesson", type_="foreignkey")
    op.drop_column("lesson", "lecture_id")
    op.drop_column("lecture_x_lesson", "ordering")
    # ### end Alembic commands ###
