"""add_lecture_columns

Revision ID: 419db5652ed1
Revises: 3cf5570a9c36
Create Date: 2025-02-16 14:36:01.519494

"""

import sqlalchemy as sa
from alembic import op

from app.db.tables import TagsType

# revision identifiers, used by Alembic.
revision = "419db5652ed1"
down_revision = "3cf5570a9c36"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lecture", sa.Column("thumbnail", sa.String(), nullable=True))
    op.add_column("lecture", sa.Column("tags", TagsType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lecture", "tags")
    op.drop_column("lecture", "thumbnail")
    # ### end Alembic commands ###
