app = 'sessionary-dawn-field-679'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'
  ignorefile = '.dockerignore'
  build-target = 'staging'

[http_service]
  internal_port = 10080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
