app = "staging-sessionary"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"
  ignorefile = '.dockerignore'
  target = "staging"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

