name: Run Frontend Tests
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "frontend/**"
jobs:
  fe-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.3

      - name: Install dependencies
        working-directory: ./frontend
        run: npm i -g yarn &&  yarn install --frozen-lockfile

      - name: Install Playwright Browsers
        working-directory: ./frontend
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          PUBLIC_API_BASE_URL: ""
        working-directory: ./frontend
        run: npx playwright test --trace on

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
