name: Update Project Card

on:
  issues:
    types: [opened, closed]

jobs:
  update-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Update Project Fields
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = context.payload.issue;
            const today = new Date().toISOString().split('T')[0];
            const isOpened = context.payload.action === 'opened';

            async function updateProjectField(projectId, itemId, fieldId, value) {
              await github.rest.projects.updateProjectCard({
                project_id: projectId,
                card_id: itemId,
                archived: false,
                note: JSON.stringify({ [fieldId]: value })
              });
            }

            try {
              // Get all project cards and filter for the current issue
              const { data: allCards } = await github.rest.projects.listCards({
                archive_state: 'not_archived'
              });
              
              const cards = allCards.filter(card => 
                card.content_url && 
                card.content_url.endsWith(`/issues/${issue.number}`)
              );
              
              for (const card of cards) {
                const { data: project } = await github.rest.projects.getColumn({
                  column_id: card.column_id
                });
                
                if (isOpened) {
                  await updateProjectField(project.project_id, card.id, 'Start Date', today);
                  console.log(`Updated Start Date to ${today} for project ${project.project_id}`);
                  
                  await updateProjectField(project.project_id, card.id, 'Team', '⚒️ Tech');
                  console.log(`Set Team to Tech for project ${project.project_id}`);
                } else {
                  await updateProjectField(project.project_id, card.id, 'End Date', today);
                  console.log(`Updated End Date to ${today} for project ${project.project_id}`);
                }
              }
            } catch (error) {
              console.error('Error updating project fields:', error);
              core.setFailed(error.message);
            }
